apiVersion: v1
kind: ReplicationController
metadata:
  namespace: netsil
  name: netsil
spec:
  replicas: 1
  selector:
    app: netsil
    component: netsil
  template:
    metadata:
      name: stream-processor
      labels:
        app: netsil
        component: netsil
        version: stable
    spec:
      containers:
      - name: netsil
        image: netsil/netsil:stable-1.0.7
        command:
        - /root/startup.sh
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2001
        - containerPort: 2003
        - containerPort: 2003
          protocol: UDP
        - containerPort: 5005
        volumeMounts:
        - name: log
          mountPath: /var/log/netsil
        - name: var-tmp
          mountPath: /var/tmp
        - name: alerts
          mountPath: /opt/netsil/alerts/data
        - name: druid-localstorage
          mountPath: /tmp/druid/localStorage
        - name: druid-realtime-segments
          mountPath: /opt/netsil/druid/realtime-segments
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
        - name: kafka-logs
          mountPath: /opt/netsil/kafka/kafka-log-dir
        - name: mysql
          mountPath: /var/lib/mysql
        - name: redis
          mountPath: /var/lib/redis
        - name: user-persistence
          mountPath: /opt/netsil/user-persistence/data
        - name: zookeeper
          mountPath: /opt/netsil/zookeeper/data
      volumes:
      - name: log
        hostPath:
          path: /var/log/netsil
      - name: var-tmp
        hostPath:
          path: /var/tmp
      - name: alerts
        hostPath:
          path: /opt/netsil/lite/alerts/data
      - name: druid-localstorage
        hostPath:
          path: /opt/netsil/lite/druid/localStorage
      - name: druid-realtime-segments
        hostPath:
          path: /opt/netsil/lite/druid/realtime-segments
      - name: elasticsearch
        hostPath:
          path: /opt/netsil/lite/elasticsearch/data
      - name: kafka-logs
        hostPath:
          path: /opt/netsil/lite/kafka/kafka-log-dir
      - name: mysql
        hostPath:
          path: /opt/netsil/lite/mysql/data
      - name: redis
        hostPath:
          path: /opt/netsil/lite/redis
      - name: user-persistence
        hostPath:
          path: /opt/netsil/lite/user-persistence/data
      - name: zookeeper
        hostPath:
          path: /opt/netsil/lite/zookeeper/data
